version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Get app Version
          command: |
            pip install requests
            python fetch_latest_release.py
            tar xvf current_release.tar.gz
      - run: 
          name: Build Docker Container
          command: docker build --build-arg APP_VERSION=$(cat current_release_version) -t catdeployed/tautulli:$(cat current_release_version) -t catdeployed/tautulli:latest .
      - run:
          name: Check if version exists
          command: docker pull catdeployed/tautulli:${APP_VERSION} && circleci step halt || true
      - run:
          name: Skip this job for Pull Requests
          command: '[[ -v CIRCLE_PR_NUMBER ]] && circleci step halt || true'
      - run:
          name: Login to Docker Hub
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run:
          name: Push to Docker Hub
          command: docker push catdeployed/tautulli
          context: Docker Hub

workflows:
  version: 2
  nightly:
    triggers:
      - schedule:
          cron: "0 * * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build
  commit:
    jobs:
      - build
